### ISSUE TITLE
No support for libs other than discord.js

### ISSUE THREAD

**Issue by LJNeon** [RealBlazeIt/patron.js#2]
If this had support for eris I'd consider using it, same probably goes for other people who use discord.io or discord.ie.

**Comment by ghost** [comment]
This is something I have considered before, however, if support were to be added for other libraries, the `Handler.js` file and the majority of the type readers would have to be entirely reworked for each additional library. This can be done, but it would be a lot of code.

**Comment by LJNeon** [comment]
How would you want to implement that? A few ideas that come to mind are:
 * A new parameter with the lib name
 * Built-in check for which lib is being used
 * Add-ons for each lib

Depending on how you want to implement it I may be able to make a PR for it.

**Comment by LJNeon** [comment]
Well, to clarify, a PR for eris support. I don't know the other js libs well enough to add them.

**Comment by ghost** [comment]
Yes, I like the name of the library passed as a string into the registry constructor, preferably in a RegistryOptions object, like the TypeReader, with the property library. Then since the the handler is constructed with the regsitry, it can just copo posto that option into the handler. There should be a LibraryHandler structure, which would case switch the different libraries, and execute the respective code. For example, the permissions check in the Handler would be placed there, since its different for all libraries. As for the type readers, they should be placed in a folder named the respective library. And there would also be a global folder, for type readers that apply to all libs, like ints and strings. This is how I would do it.

**Comment by vim2meta** [comment]
vim2meta/patron.js#3

**Comment by ghost** [comment]
implemented in #3
